task/hw6
NailShaykhrazievItis/Template pull request #10
Opened 2019-11-10 15:17 UTC by TaliyaR

![image](https://user-images.githubusercontent.com/45817710/68546274-9fb42980-03e5-11ea-8d40-538c87e1711a.gif)

2019-11-10 16:37 UTC, TaliyaR commented on app/build.gradle
> -        targetCompatibility = kotlin_version
отказывает запускаться, когда вот так указано, не пойму что делать с этим

2019-12-07 15:43 UTC, NailShaykhrazievItis requested changes

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/fragments/DescriptionGoalFragment.kt
> +        ): DescriptionGoalFragment = DescriptionGoalFragment().also {
also -> apply

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/fragments/DescriptionGoalFragment.kt
> +        private const val GOAL = "goal"
ARG_GOAL
ARG_DESCRIPTION
ARG_PLAN

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/fragments/DescriptionGoalFragment.kt
> +        tv_goal.text = arguments?.getString(GOAL)
tv_goal.text = arguments?.getString(GOAL) ?: "" чтоб если будет нулл пользователь видел пустую строку а не null

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/fragments/GoalsFragment.kt
> +            fragmentManager.also {
fragmentManager?.beginTransaction()?.apply {

зачем тебе also просто лишняя скоуп функция

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/fragments/TodayFragment.kt
> +
extra line

2019-12-07 15:43 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/MainActivity.kt
> +        supportFragmentManager.also {
supportFragmentManager.beginTransaction().apply {

2020-01-20 19:34 UTC, NailShaykhrazievItis approved these changes

2020-01-20 19:34 UTC, closed without merging