task/hw5
NailShaykhrazievItis/Template pull request #7
Opened 2019-11-02 14:00 UTC by TaliyaR

2019-11-02 14:06 UTC, TaliyaR commented
![Main Page](https://user-images.githubusercontent.com/45817710/68072097-ed4fe700-fd92-11e9-8ea8-8153f14c1059.jpg)
![Details](https://user-images.githubusercontent.com/45817710/68072117-0eb0d300-fd93-11e9-8d77-e2e14e64d03e.jpg)

2019-11-06 21:22 UTC, NailShaykhrazievItis requested changes

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/DetailsActivity.kt
> +        val name = intent?.extras?.getString(KEY_NAME) ?: "DEFAULT NAME"
"DEFAULT NAME" можно вынести в константу тоже

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/Landmark.kt
> +)
single line after class

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/LandmarkAdapter.kt
> +}
single line

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/LandmarkItemHolder.kt
> +        itemView.tv_name.text = landmark.name
itemView. - лишнее

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/LandmarkItemHolder.kt
> +import kotlinx.android.synthetic.main.item_landmark.view.*
kotlinx.android.synthetic.main.item_landmark.*

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/LandmarkItemHolder.kt
> +) : RecyclerView.ViewHolder(containerView), LayoutContainer {
LayoutContainer используется как раз для того чтоб можно напрямую к ид обращаться. Плюс это производительнее

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/LandmarkItemHolder.kt
> +}
line

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/MainActivity.kt
> +    private fun navigateToDetailsActivity(name: String, description: String, image: Int) {
пусть лучше метод принимает объект и здесь уже вытаскивать данные. Так лучше для читабельности

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_details.xml
> +        android:background="?attr/selectableItemBackgroundBorderless"
А зачем? Не оч понятно функция этого?

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_details.xml
> +        android:layout_width="match_parent"
0dp. В констреинте если ты хочешь чтоб элемент занимал все пространство от одной привязки до другой стоит использовать 0дп. У тебя привязки по краям экрана. Как раз и получается матч_парент

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_details.xml
> +        android:layout_width="match_parent"
0дп

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_details.xml
> +        android:layout_alignParentStart="true"
в констреинт лайоуте нет такого параметра. Удалить

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_landmark.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
ConstraintLayout лишняя обертка в иерархии вью. В данном случае рутовым элементом будет выступать кардвью.

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_landmark.xml
> +        android:background="@color/cardview_light_background"
отсортировать ctrl alt L

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_landmark.xml
> +                android:layout_width="match_parent"
0dp

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_landmark.xml
> +                android:background="?attr/selectableItemBackgroundBorderless"
если ты хотела добиться эффекта нажатия, то лучше дать его всему итему. Можно в ConstraintLayout переместить. Ну если хотела только для картинки, то все ок

2019-11-06 21:22 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_landmark.xml
> +
extra_line

2019-11-24 12:37 UTC, NailShaykhrazievItis approved these changes

2019-11-24 13:30 UTC, closed without merging