Homework 02.11
NailShaykhrazievItis/Template pull request #8
Opened 2019-11-03 09:45 UTC by fedotovdiana

![1](https://github.com/fedotovdiana/Template/blob/homework_02.11/1.jpg)
![2](https://github.com/fedotovdiana/Template/blob/homework_02.11/2.jpg)

2019-11-06 21:07 UTC, NailShaykhrazievItis requested changes

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/DescriptionActivity.kt
> +        val title = intent?.extras?.getString(KEY_TITLE) ?: "DEFAULT NAME"
"DEFAULT NAME" в константу вынести. У тебя строка повторяется более 2 раз

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/Film.kt
> +)
add line after class

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/FilmAdapter.kt
> +}
add line after class

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/itis/template/FilmItemHolder.kt
> +            clickLambda(film.title, film.year, film.country, film.img)
так передавай сразу объект фильм. Зачем каждый параметр по отдельности передавать. А если 27+ там будет? 
`private val clickLambda: (Film) -> Unit`

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_film.xml
> +        android:layout_width="100dp"
В андроиде обычно размеры делятся на 8. Тут ближайшее 96 будет или 104

2019-11-06 21:07 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_film.xml
> +        android:textSize="12sp"
12 слишком мелкий шрифт. Хотя бы 13, но обычно для дескрипшена используется 14 сп

2019-11-07 12:33 UTC, fedotovdiana commented on app/src/main/java/com/itis/template/FilmItemHolder.kt
> +            clickLambda(film.title, film.year, film.country, film.img)
Нужно использовать Parcelable?

2019-11-09 17:27 UTC, NailShaykhrazievItis approved these changes

2019-11-09 17:31 UTC, closed without merging